// scripts/generate_firebase_options.dart
import 'dart:io';

void main() {
  final env = Platform.environment;

  final projectId = _get('FIREBASE_PROJECT_ID');
  final messagingSenderId = _get('FIREBASE_MESSAGING_SENDER_ID');
  final storageBucket = _get('FIREBASE_STORAGE_BUCKET');
  final authDomain = _get('FIREBASE_AUTH_DOMAIN');

  final androidApiKey = _get('FIREBASE_API_KEY_ANDROID');
  final androidAppId = _get('FIREBASE_APP_ID_ANDROID');

  final iosApiKey = _get('FIREBASE_API_KEY_IOS');
  final iosAppId = _get('FIREBASE_APP_ID_IOS');

  final webApiKey = _get('FIREBASE_API_KEY_WEB');
  final webAppId = _get('FIREBASE_APP_ID_WEB');
  final webMeasurementId = env['FIREBASE_MEASUREMENT_ID_WEB'] ?? '';

  final windowsAppId = _get('FIREBASE_APP_ID_WINDOWS');
  final windowsMeasurementId = env['FIREBASE_MEASUREMENT_ID_WINDOWS'] ?? '';

  final content = '''
// Generated by generate_firebase_options.dart
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) return web;
    switch (defaultTargetPlatform) {
      case TargetPlatform.android: return android;
      case TargetPlatform.iOS: return ios;
      case TargetPlatform.macOS: return macos;
      case TargetPlatform.windows: return windows;
      case TargetPlatform.linux:
        throw UnsupportedError('Linux not configured');
      default:
        throw UnsupportedError('Platform not supported');
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: '$webApiKey',
    appId: '$webAppId',
    messagingSenderId: '$messagingSenderId',
    projectId: '$projectId',
    authDomain: '$authDomain',
    storageBucket: '$storageBucket',
    measurementId: '$webMeasurementId',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: '$androidApiKey',
    appId: '$androidAppId',
    messagingSenderId: '$messagingSenderId',
    projectId: '$projectId',
    storageBucket: '$storageBucket',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: '$iosApiKey',
    appId: '$iosAppId',
    messagingSenderId: '$messagingSenderId',
    projectId: '$projectId',
    storageBucket: '$storageBucket',
    iosBundleId: 'com.example.provaAbastecimento',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: '$iosApiKey',
    appId: '$iosAppId',
    messagingSenderId: '$messagingSenderId',
    projectId: '$projectId',
    storageBucket: '$storageBucket',
    iosBundleId: 'com.example.provaAbastecimento',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: '$webApiKey',
    appId: '$windowsAppId',
    messagingSenderId: '$messagingSenderId',
    projectId: '$projectId',
    authDomain: '$authDomain',
    storageBucket: '$storageBucket',
    measurementId: '$windowsMeasurementId',
  );
}
''';

  File('lib/firebase_options.dart').writeAsStringSync(content);
  print('firebase_options.dart gerado com sucesso!');
}

String _get(String key) {
  final value = Platform.environment[key];
  if (value == null || value.isEmpty) {
    throw Exception('ERRO: $key não encontrada! Preencha .env ou GitHub Secrets.');
  }
  return value;
}